### ISSUE TITLE
mosh users no longer appear in reports based on utmp or wtmp

### ISSUE THREAD

**Issue by cwmccabe** [altlinux/libutempter#1]
Within the past month, I noticed that users connected to my Arch-based server with mosh no longer appear in reports from the 'w' or 'last command, which rely on the utmp and wtmp files.  I asked about this on the Arch BBS and it was suggested I file a bug here.  My post on the Arch BBS is here: https://bbs.archlinux.org/viewtopic.php?pid=1914218#p1914218  If libutempter is the source of this, I am happy to provide any further information.

**Comment by ldv-alt** [comment]
Fixed in 1e05dd765de8c5c9af96cf460686928ba12e56f8.
